# Generated by Django 3.0 on 2024-01-05 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ellistest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='ellis',
        ),
    ]
