# Generated by Django 3.0 on 2024-01-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ellistest', '0002_auto_20240105_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userid',
        ),
        migrations.AlterModelTable(
            name='user',
            table='ellistest',
        ),
    ]
