# Generated by Django 3.0 on 2024-01-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ellistest', '0004_auto_20240105_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
